from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 600)
        self.scroll = QScrollArea()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.lbl_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName("lbl_name")
        self.horizontalLayout_27.addWidget(self.lbl_name)
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.name.setFont(font)
        self.name.setText("")
        self.name.setObjectName("name")
        self.horizontalLayout_27.addWidget(self.name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.lbl_addr = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_addr.setFont(font)
        self.lbl_addr.setObjectName("lbl_addr")
        self.horizontalLayout_25.addWidget(self.lbl_addr)
        self.line = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.line.setFont(font)
        self.line.setObjectName("line")
        self.horizontalLayout_25.addWidget(self.line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.lbl_phone = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_phone.setFont(font)
        self.lbl_phone.setObjectName("lbl_phone")
        self.horizontalLayout_26.addWidget(self.lbl_phone)
        self.phone = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.phone.setFont(font)
        self.phone.setText("")
        self.phone.setMaxLength(10)
        self.phone.setObjectName("phone")
        self.horizontalLayout_26.addWidget(self.phone)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.lbl_age = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_age.setFont(font)
        self.lbl_age.setObjectName("lbl_age")
        self.horizontalLayout_31.addWidget(self.lbl_age)
        self.age = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.age.setFont(font)
        self.age.setText("")
        self.age.setMaxLength(4)
        self.age.setObjectName("age")
        self.horizontalLayout_31.addWidget(self.age)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_31)
        self.verticalLayout_2.addLayout(self.horizontalLayout_32)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbm = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rbm.setFont(font)
        self.rbm.setObjectName("rbm")
        self.verticalLayout.addWidget(self.rbm)
        self.rbf = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rbf.setFont(font)
        self.rbf.setObjectName("rbf")
        self.verticalLayout.addWidget(self.rbf)
        self.rbo = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rbo.setFont(font)
        self.rbo.setObjectName("rbo")
        self.verticalLayout.addWidget(self.rbo)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.lbl_bp = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_bp.setFont(font)
        self.lbl_bp.setObjectName("lbl_bp")
        self.horizontalLayout_30.addWidget(self.lbl_bp)
        self.bp = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bp.setFont(font)
        self.bp.setText("")
        self.bp.setMaxLength(4)
        self.bp.setObjectName("bp")
        self.horizontalLayout_30.addWidget(self.bp)
        self.lbl_pulse = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_pulse.setFont(font)
        self.lbl_pulse.setObjectName("lbl_pulse")
        self.horizontalLayout_30.addWidget(self.lbl_pulse)
        self.pulse = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pulse.setFont(font)
        self.pulse.setText("")
        self.pulse.setMaxLength(4)
        self.pulse.setObjectName("pulse")
        self.horizontalLayout_30.addWidget(self.pulse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_30)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.history = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.history.setFont(font)
        self.history.setObjectName("history")
        self.gridLayout_3.addWidget(self.history, 1, 0, 1, 1)
        self.lbl_history = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_history.setFont(font)
        self.lbl_history.setObjectName("lbl_history")
        self.gridLayout_3.addWidget(self.lbl_history, 0, 0, 1, 1)
        self.symptoms = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.symptoms.setFont(font)
        self.symptoms.setObjectName("symptoms")
        self.gridLayout_3.addWidget(self.symptoms, 1, 1, 1, 1)
        self.lbl_symptoms = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_symptoms.setFont(font)
        self.lbl_symptoms.setObjectName("lbl_symptoms")
        self.gridLayout_3.addWidget(self.lbl_symptoms, 0, 1, 1, 1)
        self.lbl_medicines = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_medicines.setFont(font)
        self.lbl_medicines.setObjectName("lbl_medicines")
        self.gridLayout_3.addWidget(self.lbl_medicines, 0, 2, 1, 1)
        self.medicines = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.medicines.setFont(font)
        self.medicines.setObjectName("medicines")
        self.gridLayout_3.addWidget(self.medicines, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.lbl_amt_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_amt_2.setFont(font)
        self.lbl_amt_2.setObjectName("lbl_amt_2")
        self.horizontalLayout_28.addWidget(self.lbl_amt_2)
        self.amount_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.amount_2.setFont(font)
        self.amount_2.setText("")
        self.amount_2.setMaxLength(10)
        self.amount_2.setObjectName("amount_2")
        self.horizontalLayout_28.addWidget(self.amount_2)
        self.cb_left_2 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cb_left_2.setFont(font)
        self.cb_left_2.setObjectName("cb_left_2")
        self.horizontalLayout_28.addWidget(self.cb_left_2)
        self.left_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.left_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.left_2.setFont(font)
        self.left_2.setText("")
        self.left_2.setMaxLength(10)
        self.left_2.setObjectName("left_2")
        self.horizontalLayout_28.addWidget(self.left_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.lbl_notes = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_notes.setFont(font)
        self.lbl_notes.setObjectName("lbl_notes")
        self.horizontalLayout_29.addWidget(self.lbl_notes)
        self.notes = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.notes.setFont(font)
        self.notes.setObjectName("notes")
        self.horizontalLayout_29.addWidget(self.notes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_29)
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.verticalLayout_2.addWidget(self.submit)

        self.scroll.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scroll.setWidgetResizable(True)
        self.scroll.setWidget(self.centralwidget)

        MainWindow.setCentralWidget(self.scroll)

        # MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1239, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_name.setText(_translate("MainWindow", "Name:"))
        self.lbl_addr.setText(_translate("MainWindow", "Address: "))
        self.lbl_phone.setText(_translate("MainWindow", "Phone:"))
        self.lbl_age.setText(_translate("MainWindow", "Age:"))
        self.rbm.setText(_translate("MainWindow", "Male"))
        self.rbf.setText(_translate("MainWindow", "Female"))
        self.rbo.setText(_translate("MainWindow", "Other"))
        self.lbl_bp.setText(_translate("MainWindow", "BP:"))
        self.lbl_pulse.setText(_translate("MainWindow", "Pulse:"))
        self.lbl_history.setText(_translate("MainWindow", "History"))
        self.lbl_symptoms.setText(_translate("MainWindow", "Symptoms"))
        self.lbl_medicines.setText(_translate("MainWindow", "Medicines"))
        self.lbl_amt_2.setText(_translate("MainWindow", "Amount:"))
        self.cb_left_2.setText(_translate("MainWindow", "Left"))
        self.lbl_notes.setText(_translate("MainWindow", "Notes:"))
        self.submit.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
